### ISSUE TITLE
Hi! Beginner Installation on NixOS

### ISSUE THREAD

**Issue by 80aff123-9163-4f3e-a93d-4a2f35af9be1** [bqv/guix#1]
Hi,

I am running nixos.

How can I install this?

Do I need to set up flakes in order to install it?

Is it possible to install guix with this nix module on a non-nixos distro (e.g. ubuntu, debian, centos)

Any help is greatly appreciated.

**Comment by bqv** [comment]
Yes, this will in most cases require a flakey setup to work. The only other alternative would be to use github.com/edolstra/flake-compat to bridge the gap.

It doesn't quite make any sense to use a nixos module outside nixos, so I wouldn't bother. Guix supports rootless installs directly anyway

**Comment by bqv** [comment]
I'll close this, but let me know if you need more of a hand with this, or speak to someone at irc://freenode.net/#nixos or irc://freenode.net/#guix

**Comment by therealpxc** [comment]
> It doesn't quite make any sense to use a nixos module outside nixos, so I wouldn't bother. Guix supports rootless installs directly anyway

A weird thought: since GNU Shepherd is a little less presumptuous than systemd, doesn't it *almost* make sense to use a module like that with something like home-manager? There aren't a *ton* of benefits, but I can think of a couple:

  * one thing to bootstrap instead of two
  * guix-daemon can get set up automatically by home-manager as a systemd user service
  * the [official instructions](https://guix.gnu.org/manual/en/html_node/Binary-Installation.html) for Guix installation still say you need root, and the [instructions](https://github.com/pjotrp/guix-notes/blob/master/GUIX-NO-ROOT.org#building-packages-to-run-without-proot) I found online for non-root installs (a) are a little involved and (b) use pivot-root (which is slow) and then a non-standard prefix (which breaks binary caching)
    - home manager could use [nix-user-chroot](https://github.com/nix-community/nix-user-chroot) where user namespaces are available, which (in my experience) has better performance and compatibility than a pivot_root environment

What do you think?

**Comment by bqv** [comment]
It's an interesting idea. Obviously the biggest problem with it being at user-level is having the guix-daemon running with write access to /gnu, which you solve with nix-user-chroot, but then all calls to guix need to enter the same namespace. At a point it feels like somewhat creating a lightweight container with guix in it.

I think I definitely prefer the nixos module, but if you'd like to add a home-manager module to this flake too I don't see why I wouldn't merge that PR.

For the record, I was considering `proot` for rootless installs, the same method people generally use with nix to avoid nonstandard cachedirs - that might still cause slowdowns due to the path rewriting but it's better than nothing.
